services:
  postgres-master:
    image: docker.io/bitnami/postgresql:latest
    container_name: cozybox_master_db
    ports:
      - "5500:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replication_user
      POSTGRESQL_REPLICATION_PASSWORD: replication_password
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: cozybox
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: "true"
    volumes:
      - cozybox_postgres_master_data:/bitnami/postgresql
    networks:
      - cozybox_network_db

  postgres-replica1:
    image: docker.io/bitnami/postgresql:latest
    container_name: cozybox_replica_db
    depends_on:
      - postgres-master
    ports:
      - "5501:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replication_user
      POSTGRESQL_REPLICATION_PASSWORD: replication_password
      POSTGRESQL_MASTER_HOST: postgres-master
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_PASSWORD: password
    volumes:
      - cozybox_postgres_replica1_data:/bitnami/postgresql
    networks:
      - cozybox_network_db

  redis:
    image: redis:8.4.0
    container_name: cozybox_redis
    restart: always
    command: redis-server --appendonly yes --requirepass cmjpqcqbc000104kzca2o86rw
    ports:
      - "6379:6379"
    volumes:
      - cozybox_redis_data:/data
    networks:
      - cozybox_network_db

  minio:
    image: minio/minio:latest
    container_name: cozybox_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - cozybox_minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - cozybox_network_db

networks:
  cozybox_network_db:
    driver: bridge

volumes:
  cozybox_minio_data:
  cozybox_postgres_master_data:
  cozybox_postgres_replica1_data:
  cozybox_redis_data: